# Problem(a)

In [1]:
# from matplotlib import pyplot
import os

#define a function to count the document number 
def Count(dirname):
  count=0
  for item in os.listdir(dirname):
    count+=1
  return count

counter=[]

#plot the histogram for 20 topics
for dir in os.listdir('20news-bydate-train'):
  dir_name='20news-bydate-train/'+dir
  count1=Count(dir_name)
  counter.append(count1)

i=0;

for dir in os.listdir('20news-bydate-test'):
  #print counter[i],'\n'
  dir_name='20news-bydate-test/'+dir
  count2=Count(dir_name)
  counter[i]+=count2
  #print counter[i],'\n'
  i+=1
  
#count the document number for the two groups
new_counter=[0,0]
for dir in os.listdir('20news-bydate-train'):
  if(dir=='comp.graphics' or dir=='comp.os.ms-windows.misc' or dir=='comp.sys.ibm.pc.hardware' or dir=='comp.sys.mac.hardware'):
    dir_name='20news-bydate-train/'+dir
    count1=Count(dir_name)
    new_counter[0]+=count1
    #print (new_counter[0],'\n')
  if(dir=='rec.autos' or dir=='rec.motorcycles' or dir=='rec.sport.baseball' or dir=='rec.sport.hockey'):
    dir_name='20news-bydate-train/'+dir
    count1=Count(dir_name)
    new_counter[1]+=count1
    #print (new_counter[1],'\n')
    
for dir in os.listdir('20news-bydate-test'):
  if(dir=='comp.graphics' or dir=='comp.os.ms-windows.misc' or dir=='comp.sys.ibm.pc.hardware' or dir=='comp.sys.mac.hardware'):
    dir_name='20news-bydate-test/'+dir
    count2=Count(dir_name)
    new_counter[0]+=count2
    #print (new_counter[0],'\n')
  if(dir=='rec.autos' or dir=='rec.motorcycles' or dir=='rec.sport.baseball' or dir=='rec.sport.hockey'):
    dir_name='20news-bydate-test/'+dir
    count2=Count(dir_name)
    new_counter[1]+=count2
    #print (new_counter[1],'\n')

print ('Group1 is: ',new_counter[0],', Group2 is: ',new_counter[1])

Group1 is:  3903 , Group2 is:  3979


In [2]:
import numpy as np
import matplotlib.pyplot as plt
n = 20
values = (counter[0],counter[1],counter[2],counter[3],counter[4],counter[5],counter[6],counter[7],counter[8],counter[9],counter[10],counter[11],counter[12],counter[13],counter[14],counter[15],counter[16],counter[17],counter[18],counter[19])
fig, ax = plt.subplots()
index = np.arange(n)
bar_width = 0.35
opacity = 1.0
bars = plt.bar(index, values, bar_width,alpha = opacity, color = 'b')
plt.xlabel('Topics')
plt.xlabel('Documents')
plt.title('Number of documents per topic')
plt.xticks(index + bar_width, ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'))
plt.ylim(0,1000)
plt.legend()
plt.tight_layout()
plt.show()

C:\Users\Ziyin\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py:519: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "


# Problem(b)

In [3]:
from sklearn.feature_extraction import text
import re
import nltk
import string
#nltk.download()

stop_words = text.ENGLISH_STOP_WORDS

from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english")

def tokenizer_fun(text):
    new_text = re.sub(r'[^A-Za-z]', " ", text)
    tokens =[word for sent in nltk.sent_tokenize(new_text) for word in nltk.word_tokenize(sent)]
    new_tokens = []
    for token in tokens:
        if re.search('[a-zA-Z]{2,}', token):
            new_tokens.append(token)     
    stem = [stemmer.stem(t) for t in new_tokens]
    return stem

from sklearn.datasets import fetch_20newsgroups
all_data = fetch_20newsgroups(subset='all', shuffle=True, random_state=42, remove=('headers','footers','quotes'))

from sklearn.feature_extraction.text import TfidfVectorizer
TFxIDF = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}',)
TFxIDF_data = TFxIDF.fit_transform(all_data.data)
count = TFxIDF_data.shape

print (count)

(18846, 72399)


# Problem(c)

In [4]:
list=['comp.sys.ibm.pc.hardware','comp.sys.mac.hardware','misc.forsale','soc.religion.christian']

for category in list:
    categories = [category]
    sub_data = fetch_20newsgroups(subset='all', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
    TFxIDF_sub = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, max_features=10, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}')
    sub_count = TFxIDF_sub.fit_transform(sub_data.data)
    #print (sub_count)
    print (TFxIDF_sub.vocabulary_.keys())
    

dict_keys(['card', 'drive', 'ani', 'scsi', 'work', 'mb', 'control', 'problem', 'use', 'disk'])
dict_keys(['drive', 'appl', 'mac', 'ani', 'like', 'work', 'know', 'monitor', 'problem', 'use'])
dict_keys(['includ', 'drive', 'sell', 'pleas', 'new', 'ship', 'sale', 'price', 'offer', 'use'])
dict_keys(['god', 'peopl', 'believ', 'think', 'jesus', 'christian', 'church', 'sin', 'say', 'know'])


# Problem(d)

In [5]:
from sklearn.decomposition import TruncatedSVD
X = TruncatedSVD(n_components=50)
LSI = X.fit_transform(TFxIDF_data)
#print (LSI)

# Problem(e)

### Define functions to get data or LSI for train/test set

In [19]:
categories = ['comp.graphics','comp.os.ms-windows.misc','comp.sys.ibm.pc.hardware','comp.sys.ibm.pc.hardware','rec.autos','rec.motorcycles','rec.sport.baseball','rec.sport.hockey']

def data_fun(train_or_test):
    if(train_or_test == 'train'):
        data = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
    if(train_or_test == 'test'):
        data = fetch_20newsgroups(subset='test', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
    return data  

def LSI_fun(train_or_test):
    if(train_or_test == 'train'):
        data = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
        TFxIDF_sub = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}',)
        TFxIDF_sub_data = TFxIDF_sub.fit_transform(data.data)
        Y = TruncatedSVD(n_components=50)
        sub_LSI = Y.fit_transform(TFxIDF_sub_data)
    if(train_or_test == 'test'):
        data = fetch_20newsgroups(subset='test', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
        TFxIDF_sub = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}',)
        TFxIDF_sub_data = TFxIDF_sub.fit_transform(data.data)
        Y = TruncatedSVD(n_components=50)
        sub_LSI = Y.fit_transform(TFxIDF_sub_data)
    return sub_LSI 

new_LSI = LSI_fun('train')
print (new_LSI.shape)

new_LSI = LSI_fun('test')
print (new_LSI.shape)

(4154, 50)
(2765, 50)


### SVM classifier

In [21]:
from sklearn import svm
lin_clf = svm.LinearSVC()
# print(all_data.target)
train_LSI = LSI_fun('train')
train_set = data_fun('train')

train_target_group = [ int(x / 10) for x in train_set.target]
# print(train_target_group)
print(train_set.target[0:20])
# lin_clf.fit(train_LSI, train_set.target)
lin_clf.fit(train_LSI, train_target_group)
#lin_clf.fit(train_LSI, train_set.target)

[5 5 7 4 6 1 2 4]


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [22]:
test_LSI = LSI_fun('test')
print(test_LSI.shape)
svm_predicted = lin_clf.predict(test_LSI)
print (svm_predicted[0:20])

(2765, 50)
[0 1 0 1 1 0 0 1 1 1 0 0 0 0 1 0 1 0 1 0]


### SVM-ROC Curve

In [24]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
test_set = data_fun('test')
test_target_group = [ int(x / 10) for x in test_set.target]
y_score_test = lin_clf.decision_function(test_LSI)


print(test_target_group[0:10])
print(y_score_test.shape)
print(y_score_test[0:10])

fpr, tpr, thresholds = roc_curve(test_target_group, y_score_test)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, lw=1, label='ROC fold (area = %0.2f)' % roc_auc)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.show()

[1, 0, 1, 0]
(2765,)
[-0.8258543   1.07265862 -0.22201801  1.10889407]


### SVM-Confusion Matrix

In [25]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_target_group, svm_predicted)

array([[ 342,  833],
       [1394,  196]])

### SVM-Accuracy, Precision, Recall

In [26]:
from sklearn.metrics import accuracy_score
svm_accuracy = accuracy_score(test_target_group, svm_predicted)
print (svm_accuracy)

0.194575045208


In [11]:
from sklearn.metrics import precision_score
svm_precision_score = precision_score(test_target_group, svm_predicted)
print (svm_precision_score)

0.650690283928


In [12]:
from sklearn.metrics import recall_score
svm_recall_score = recall_score(test_target_group, svm_predicted)
print (svm_recall_score)

0.679358172423


### SVM-Recall and Precision

In [21]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
precision = dict()
recall = dict()
average_precision = dict()
precision, recall, _ = precision_recall_curve(test_target_group,y_score_test)
average_precision = average_precision_score(test_target_group, y_score_test)
print (precision[0:10])
print (recall[0:10])

[ 0.48837827  0.48831031  0.48837518  0.48844007  0.48850498  0.48856991
  0.48863485  0.48869981  0.48876479  0.48882979]
[ 1.          0.99972804  0.99972804  0.99972804  0.99972804  0.99972804
  0.99972804  0.99972804  0.99972804  0.99972804]


# Problem(f)

# Problem(g)

### NB classifier

In [43]:
from sklearn.naive_bayes import GaussianNB
nb_clf = GaussianNB()
nb_clf.fit(train_LSI, train_target_group)
nb_predicted = naive_clf.predict(test_LSI)
print (nb_predicted.shape)
print (nb_predicted[0:10])

(7532,)
[1 0 1 1 1 0 0 0 0 0]


### NB-ROC Curve

In [44]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
test_set = data_fun('test')
test_target_group = [ int(x / 10) for x in test_set.target]
y_score_test_nb = nb_clf.predict_proba(test_LSI)[:,1]


print(y_score_test_nb.shape)
print(y_score_test_nb[0:10])

fpr, tpr, thresholds = roc_curve(test_target_group, y_score_test_nb)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, lw=1, label='ROC fold (area = %0.2f)' % roc_auc)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.show()

(7532,)
[  9.98215497e-01   3.75858161e-04   9.99999024e-01   9.62466911e-01
   1.00000000e+00   1.32571625e-02   2.31623718e-04   7.25040868e-04
   8.01744106e-04   2.58492837e-02]


### NB-Confusion Matrix

In [45]:
from sklearn.metrics import confusion_matrix

confusion_matrix(test_target_group, nb_predicted)

array([[2629, 1226],
       [1965, 1712]])

### NB-Accuracy, Precision, Recall

In [46]:
from sklearn.metrics import accuracy_score
nb_accuracy = accuracy_score(test_target_group, nb_predicted)
print (nb_accuracy)

0.5763409453


In [47]:
from sklearn.metrics import precision_score
nb_precision_score = precision_score(test_target_group, nb_predicted)
print (nb_precision_score)

0.582709326072


In [48]:
from sklearn.metrics import recall_score
nb_recall_score = recall_score(test_target_group, nb_predicted)
print (nb_recall_score)

0.465596954039


### NB-Recall and Precision

In [74]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
y_score_test_nb = nb_clf.predict_proba(test_LSI)[:,1]
precision = dict()
recall = dict()
average_precision = dict()
precision, recall, _ = precision_recall_curve(test_target_group,y_score_test_nb)
average_precision = average_precision_score(test_target_group, y_score_test_nb)
print (precision[0:10])
print (recall[0:10])

[ 0.48818375  0.48811579  0.48804781  0.48811263  0.48817747  0.48824233
  0.48817433  0.4882392   0.48830409  0.488369  ]
[ 1.          0.99972804  0.99945608  0.99945608  0.99945608  0.99945608
  0.99918412  0.99918412  0.99918412  0.99918412]


# Problem(h)

### LR classifier

In [61]:
from sklearn import linear_model, datasets
logreg = linear_model.LogisticRegression(C=1e5)
logreg.fit(train_LSI, train_target_group)
lr_predicted = logreg.predict(test_LSI)
print (lr_predicted.shape)
print (lr_predicted[0:10])

(7532,)
[0 1 0 1 0 1 1 0 0 0]


### LR-ROC Curve

In [68]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
test_set = data_fun('test')
test_target_group = [ int(x / 10) for x in test_set.target]
y_score_test_lr = logreg.decision_function(test_LSI)
#y_score_test_lr = logreg.predict_proba(test_LSI)[:,1]

print(y_score_test_lr.shape)
print(y_score_test_lr[0:10])

fpr, tpr, thresholds = roc_curve(test_target_group, y_score_test_lr)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, lw=1, label='ROC fold (area = %0.2f)' % roc_auc)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.show()

(7532,)
[-3.26845382  0.16877386 -4.95827412  3.6898236  -6.72444147  0.28711841
  2.15477778 -6.0935701  -2.88783226 -2.91196545]


### LR-Confusion Matrix

In [69]:
from sklearn.metrics import confusion_matrix

confusion_matrix(test_target_group, lr_predicted)

array([[2535, 1320],
       [1356, 2321]])

### LR-Accuracy, Precision, Recall

In [70]:
from sklearn.metrics import accuracy_score
lr_accuracy = accuracy_score(test_target_group, lr_predicted)
print (lr_accuracy)

0.644715878917


In [71]:
from sklearn.metrics import precision_score
lr_precision_score = precision_score(test_target_group, lr_predicted)
print (lr_precision_score)

0.63746223565


In [72]:
from sklearn.metrics import recall_score
lr_recall_score = recall_score(test_target_group, lr_predicted)
print (lr_recall_score)

0.631221104161


### LR-Recall and Precision

In [73]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
y_score_test_lr = logreg.decision_function(test_LSI)
precision = dict()
recall = dict()
average_precision = dict()
precision, recall, _ = precision_recall_curve(test_target_group,y_score_test_lr)
average_precision = average_precision_score(test_target_group, y_score_test_lr)
print (precision[0:10])
print (recall[0:10])

[ 0.49000533  0.48993736  0.49000267  0.49006799  0.49013333  0.49019869
  0.49026407  0.49019608  0.49026147  0.49032688]
[ 1.          0.99972804  0.99972804  0.99972804  0.99972804  0.99972804
  0.99972804  0.99945608  0.99945608  0.99945608]
