# Problem(a)

In [1]:
# from matplotlib import pyplot
import os

#define a function to count the document number 
def Count(dirname):
  count=0
  for item in os.listdir(dirname):
    count+=1
  return count

counter=[]

#plot the histogram for 20 topics
for dir in os.listdir('20news-bydate-train'):
  dir_name='20news-bydate-train/'+dir
  count1=Count(dir_name)
  counter.append(count1)

i=0;

for dir in os.listdir('20news-bydate-test'):
  #print counter[i],'\n'
  dir_name='20news-bydate-test/'+dir
  count2=Count(dir_name)
  counter[i]+=count2
  #print counter[i],'\n'
  i+=1
  
#count the document number for the two groups
new_counter=[0,0]
for dir in os.listdir('20news-bydate-train'):
  if(dir=='comp.graphics' or dir=='comp.os.ms-windows.misc' or dir=='comp.sys.ibm.pc.hardware' or dir=='comp.sys.mac.hardware'):
    dir_name='20news-bydate-train/'+dir
    count1=Count(dir_name)
    new_counter[0]+=count1
    #print (new_counter[0],'\n')
  if(dir=='rec.autos' or dir=='rec.motorcycles' or dir=='rec.sport.baseball' or dir=='rec.sport.hockey'):
    dir_name='20news-bydate-train/'+dir
    count1=Count(dir_name)
    new_counter[1]+=count1
    #print (new_counter[1],'\n')
    
for dir in os.listdir('20news-bydate-test'):
  if(dir=='comp.graphics' or dir=='comp.os.ms-windows.misc' or dir=='comp.sys.ibm.pc.hardware' or dir=='comp.sys.mac.hardware'):
    dir_name='20news-bydate-test/'+dir
    count2=Count(dir_name)
    new_counter[0]+=count2
    #print (new_counter[0],'\n')
  if(dir=='rec.autos' or dir=='rec.motorcycles' or dir=='rec.sport.baseball' or dir=='rec.sport.hockey'):
    dir_name='20news-bydate-test/'+dir
    count2=Count(dir_name)
    new_counter[1]+=count2
    #print (new_counter[1],'\n')

print ('Group1 is: ',new_counter[0],', Group2 is: ',new_counter[1])

Group1 is:  3903 , Group2 is:  3979


In [2]:
import numpy as np
import matplotlib.pyplot as plt
n = 20
values = (counter[0],counter[1],counter[2],counter[3],counter[4],counter[5],counter[6],counter[7],counter[8],counter[9],counter[10],counter[11],counter[12],counter[13],counter[14],counter[15],counter[16],counter[17],counter[18],counter[19])
fig, ax = plt.subplots()
index = np.arange(n)
bar_width = 0.35
opacity = 1.0
bars = plt.bar(index, values, bar_width,alpha = opacity, color = 'b')
plt.xlabel('Topics')
plt.xlabel('Documents')
plt.title('Number of documents per topic')
plt.xticks(index + bar_width, ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'))
plt.ylim(0,1000)
plt.legend()
plt.tight_layout()
plt.show()

C:\Users\Ziyin\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py:519: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "


# Problem(b)

In [3]:
from sklearn.feature_extraction import text
import re
import nltk 
import string
#nltk.download()

stop_words = text.ENGLISH_STOP_WORDS

from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english")

def tokenizer_fun(text):
    new_text = re.sub(r'[^A-Za-z]', " ", text)
    tokens =[word for sent in nltk.sent_tokenize(new_text) for word in nltk.word_tokenize(sent)]
    new_tokens = []
    for token in tokens:
        if re.search('[a-zA-Z]{2,}', token):
            new_tokens.append(token)     
    stem = [stemmer.stem(t) for t in new_tokens]
    return stem

from sklearn.datasets import fetch_20newsgroups
all_data = fetch_20newsgroups(subset='all', shuffle=True, random_state=42, remove=('headers','footers','quotes'))

from sklearn.feature_extraction.text import TfidfVectorizer
TFxIDF = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}',)
TFxIDF_data = TFxIDF.fit_transform(all_data.data)
count = TFxIDF_data.shape

print (count)

(18846, 72399)


# Problem(c)

In [4]:
list=['comp.sys.ibm.pc.hardware','comp.sys.mac.hardware','misc.forsale','soc.religion.christian']

for category in list:
    categories = [category]
    sub_data = fetch_20newsgroups(subset='all', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
    TFxIDF_sub = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, max_features=10, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}')
    sub_count = TFxIDF_sub.fit_transform(sub_data.data)
    #print (sub_count)
    print (TFxIDF_sub.vocabulary_.keys())
    

dict_keys(['mb', 'ani', 'disk', 'work', 'problem', 'drive', 'card', 'use', 'control', 'scsi'])
dict_keys(['drive', 'know', 'mac', 'problem', 'like', 'appl', 'monitor', 'work', 'use', 'ani'])
dict_keys(['includ', 'sale', 'offer', 'drive', 'sell', 'ship', 'price', 'new', 'use', 'pleas'])
dict_keys(['church', 'think', 'peopl', 'god', 'jesus', 'say', 'christian', 'sin', 'know', 'believ'])


# Problem(d)

In [5]:
from sklearn.decomposition import TruncatedSVD
X = TruncatedSVD(n_components=50)
LSI = X.fit_transform(TFxIDF_data)
#print (LSI)

# Problem(e)

#### Define functions to get data or LSI for train/test set

In [6]:
categories = ['comp.graphics','comp.os.ms-windows.misc','comp.sys.ibm.pc.hardware','comp.sys.ibm.pc.hardware','rec.autos','rec.motorcycles','rec.sport.baseball','rec.sport.hockey']

def data_fun(train_or_test):
    if(train_or_test == 'train'):
        data = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
    if(train_or_test == 'test'):
        data = fetch_20newsgroups(subset='test', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
    return data  

def LSI_fun(train_or_test):
    if(train_or_test == 'train'):
        data = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
        TFxIDF_sub = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}',)
        TFxIDF_sub_data = TFxIDF_sub.fit_transform(data.data)
        Y = TruncatedSVD(n_components=50)
        sub_LSI = Y.fit_transform(TFxIDF_sub_data)
    if(train_or_test == 'test'):
        data = fetch_20newsgroups(subset='test', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
        TFxIDF_sub = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}',)
        TFxIDF_sub_data = TFxIDF_sub.fit_transform(data.data)
        Y = TruncatedSVD(n_components=50)
        sub_LSI = Y.fit_transform(TFxIDF_sub_data)
    return sub_LSI 

#new_LSI = LSI_fun('train')
#print (new_LSI.shape)

#new_LSI = LSI_fun('test')
#print (new_LSI.shape)

#### SVM classifier

In [7]:
from sklearn import svm
lin_clf = svm.LinearSVC()
# print(all_data.target)
train_LSI = LSI_fun('train')
train_set = data_fun('train')

train_target_group = [ int(x / 4) for x in train_set.target]
# print(train_target_group)
print(train_set.target[0:20])
# lin_clf.fit(train_LSI, train_set.target)
lin_clf.fit(train_LSI, train_target_group)
#lin_clf.fit(train_LSI, train_set.target)

[5 5 7 4 6 1 2 4 6 0 7 2 0 7 5 7 5 2 5 5]


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [8]:
test_LSI = LSI_fun('test')
print(test_LSI.shape)
svm_predicted = lin_clf.predict(test_LSI)
print (svm_predicted[0:20])

(2765, 50)
[1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 1 1 0 1 0]


#### SVM-ROC Curve

In [9]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
test_set = data_fun('test')
test_target_group = [ int(x / 4) for x in test_set.target]
y_score_test = lin_clf.decision_function(test_LSI)


#print(test_target_group[0:10])
#print(y_score_test.shape)
#print(y_score_test[0:10])

fpr, tpr, thresholds = roc_curve(test_target_group, y_score_test)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, lw=1, label='ROC fold (area = %0.2f)' % roc_auc)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.show()

#### SVM-Confusion Matrix

In [10]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_target_group, svm_predicted)

array([[ 962,  213],
       [ 456, 1134]])

#### SVM-Accuracy, Precision, Recall

In [11]:
from sklearn.metrics import accuracy_score
svm_accuracy = accuracy_score(test_target_group, svm_predicted)
print (svm_accuracy)

0.758047016275


In [12]:
from sklearn.metrics import precision_score
svm_precision_score = precision_score(test_target_group, svm_predicted)
print (svm_precision_score)

0.841870824053


In [13]:
from sklearn.metrics import recall_score
svm_recall_score = recall_score(test_target_group, svm_predicted)
print (svm_recall_score)

0.71320754717


#### SVM-Recall and Precision

In [14]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
precision = dict()
recall = dict()
average_precision = dict()
precision, recall, _ = precision_recall_curve(test_target_group,y_score_test)
average_precision = average_precision_score(test_target_group, y_score_test)
print (precision[0:10])
print (recall[0:10])

[ 0.5758783   0.57572464  0.57593331  0.57614213  0.57635111  0.57656023
  0.57676951  0.57697894  0.57718852  0.57739826]
[ 1.          0.99937107  0.99937107  0.99937107  0.99937107  0.99937107
  0.99937107  0.99937107  0.99937107  0.99937107]


# Problem(f)

# Problem(g)

#### NB classifier

In [15]:
from sklearn.naive_bayes import GaussianNB
nb_clf = GaussianNB()
nb_clf.fit(train_LSI, train_target_group)
nb_predicted = nb_clf.predict(test_LSI)
print (nb_predicted.shape)
print (nb_predicted[0:10])

(2765,)
[1 0 1 0 0 0 1 0 0 1]


#### NB-ROC Curve

In [16]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
test_set = data_fun('test')
test_target_group = [ int(x / 4) for x in test_set.target]
y_score_test_nb = nb_clf.predict_proba(test_LSI)[:,1]


print(y_score_test_nb.shape)
print(y_score_test_nb[0:10])

fpr, tpr, thresholds = roc_curve(test_target_group, y_score_test_nb)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, lw=1, label='ROC fold (area = %0.2f)' % roc_auc)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.show()

(2765,)
[  9.99981017e-01   2.21490497e-05   9.99995834e-01   2.81952490e-20
   4.75679624e-03   1.10226832e-50   9.99951101e-01   1.58551558e-06
   3.41865903e-01   9.99985624e-01]


#### NB-Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix

confusion_matrix(test_target_group, nb_predicted)

array([[929, 246],
       [742, 848]])

#### NB-Accuracy, Precision, Recall

In [18]:
from sklearn.metrics import accuracy_score
nb_accuracy = accuracy_score(test_target_group, nb_predicted)
print (nb_accuracy)

0.642676311031


In [19]:
from sklearn.metrics import precision_score
nb_precision_score = precision_score(test_target_group, nb_predicted)
print (nb_precision_score)

0.775137111517


In [20]:
from sklearn.metrics import recall_score
nb_recall_score = recall_score(test_target_group, nb_predicted)
print (nb_recall_score)

0.533333333333


#### NB-Recall and Precision

In [21]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
y_score_test_nb = nb_clf.predict_proba(test_LSI)[:,1]
precision = dict()
recall = dict()
average_precision = dict()
precision, recall, _ = precision_recall_curve(test_target_group,y_score_test_nb)
average_precision = average_precision_score(test_target_group, y_score_test_nb)
print (precision[0:10])
print (recall[0:10])

[ 0.57504521  0.69976771  0.70151869  0.70211516  0.70271868  0.70219065
  0.70243035  0.70284698  0.70326409  0.70434265]
[ 1.          0.75786164  0.75534591  0.75157233  0.74779874  0.74591195
  0.74528302  0.74528302  0.74528302  0.74465409]


# Problem(h)

#### LR classifier

In [22]:
from sklearn import linear_model, datasets
logreg = linear_model.LogisticRegression(C=1e5)
logreg.fit(train_LSI, train_target_group)
lr_predicted = logreg.predict(test_LSI)
print (lr_predicted.shape)
print (lr_predicted[0:10])

(2765,)
[1 0 1 0 1 1 0 1 0 1]


#### LR-ROC Curve

In [23]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
test_set = data_fun('test')
test_target_group = [ int(x / 4) for x in test_set.target]
y_score_test_lr = logreg.decision_function(test_LSI)
#y_score_test_lr = logreg.predict_proba(test_LSI)[:,1]

print(y_score_test_lr.shape)
print(y_score_test_lr[0:10])

fpr, tpr, thresholds = roc_curve(test_target_group, y_score_test_lr)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, lw=1, label='ROC fold (area = %0.2f)' % roc_auc)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.show()

(2765,)
[  0.99116574  -1.77739445   0.49283749 -13.4189053    6.31897121
   8.96282951  -0.0274014    2.17361211  -5.2876063    1.90199889]


#### LR-Confusion Matrix

In [24]:
from sklearn.metrics import confusion_matrix

confusion_matrix(test_target_group, lr_predicted)

array([[ 933,  242],
       [ 534, 1056]])

#### LR-Accuracy, Precision, Recall

In [25]:
from sklearn.metrics import accuracy_score
lr_accuracy = accuracy_score(test_target_group, lr_predicted)
print (lr_accuracy)

0.719349005425


In [26]:
from sklearn.metrics import precision_score
lr_precision_score = precision_score(test_target_group, lr_predicted)
print (lr_precision_score)

0.813559322034


In [27]:
from sklearn.metrics import recall_score
lr_recall_score = recall_score(test_target_group, lr_predicted)
print (lr_recall_score)

0.664150943396


#### LR-Recall and Precision

In [28]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
y_score_test_lr = logreg.decision_function(test_LSI)
precision = dict()
recall = dict()
average_precision = dict()
precision, recall, _ = precision_recall_curve(test_target_group,y_score_test_lr)
average_precision = average_precision_score(test_target_group, y_score_test_lr)
print (precision[0:10])
print (recall[0:10])

[ 0.57650471  0.57635111  0.57656023  0.57676951  0.57697894  0.57718852
  0.57739826  0.57760814  0.57781818  0.57802837]
[ 1.          0.99937107  0.99937107  0.99937107  0.99937107  0.99937107
  0.99937107  0.99937107  0.99937107  0.99937107]


# Part (i)

#### Define functions to get data or LSI for train/test set

In [29]:
categories_i = ['comp.sys.ibm.pc.hardware','comp.sys.mac.hardware','misc.forsale','soc.religion.christian']

def data_fun_i(train_or_test):
    if(train_or_test == 'train'):
        data = fetch_20newsgroups(subset='train', categories=categories_i, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
    if(train_or_test == 'test'):
        data = fetch_20newsgroups(subset='test', categories=categories_i, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
    return data

def LSI_fun_i(train_or_test):
    if(train_or_test == 'train'):
        data = fetch_20newsgroups(subset='train', categories=categories_i, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
        TFxIDF_sub = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}',)
        TFxIDF_sub_data = TFxIDF_sub.fit_transform(data.data)
        Y = TruncatedSVD(n_components=50)
        sub_LSI = Y.fit_transform(TFxIDF_sub_data)
    if(train_or_test == 'test'):
        data = fetch_20newsgroups(subset='test', categories=categories_i, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
        TFxIDF_sub = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}',)
        TFxIDF_sub_data = TFxIDF_sub.fit_transform(data.data)
        Y = TruncatedSVD(n_components=50)
        sub_LSI = Y.fit_transform(TFxIDF_sub_data)
    return sub_LSI

In [30]:
from sklearn.multiclass import OneVsRestClassifier 
from sklearn.multiclass import OneVsOneClassifier 
from sklearn.svm import LinearSVC
train_LSI_i = LSI_fun_i('train')
train_set_i = data_fun_i('train')
test_LSI_i = LSI_fun_i('test')
test_set_i = data_fun_i('test')
#train_target_group_i = [ int(x / 10) for x in train_set_i.target]
#test_target_group_i = [int(x / 10) for x in test_set_i.target]

## one vs rest classifier

In [47]:
ovr_classifier_i = OneVsRestClassifier (LinearSVC())
ovr_classifier_i.fit(train_LSI_i, train_set_i.target)
ovr_predict_i = ovr_classifier_i.predict(test_LSI_i)
#print (ovr_predict_i[0:4])
print (ovr_predict_i)

[2 0 2 ..., 0 2 3]


#### OVR-Confusion Matrix

In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_set_i.target, ovr_predict_i)

array([[111, 217,  55,   9],
       [127, 113, 130,  15],
       [ 34,  47, 302,   7],
       [  0,   3,  22, 373]])

#### OVR-Accuracy, Precision, Recall

In [33]:
from sklearn.metrics import accuracy_score
ovr_accuracy = accuracy_score(test_set_i.target, ovr_predict_i)
print (ovr_accuracy)

0.574440894569


In [34]:
from sklearn.metrics import precision_score
ovr_precision_score = precision_score(test_set_i.target, ovr_predict_i,average='weighted')
print (ovr_precision_score)

0.558027296054


In [35]:
from sklearn.metrics import recall_score
ovr_recall_score = recall_score(test_set_i.target, ovr_predict_i,average='weighted')
print (ovr_recall_score)

0.574440894569


## one vs one classifier

In [36]:
ovo_classifier_i = OneVsOneClassifier (LinearSVC())
ovo_classifier_i.fit(train_LSI_i, train_set_i.target)
ovo_predict_i = ovo_classifier_i.predict(test_LSI_i)
print (ovo_predict_i.shape)
print (ovo_predict_i)

(1565,)
[2 0 2 ..., 0 2 3]


#### OVO-Confusion Matrix

In [37]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_set_i.target, ovo_predict_i)

array([[120, 212,  60,   0],
       [135, 113, 133,   4],
       [ 34,  45, 307,   4],
       [  1,  10,  30, 357]])

#### OVO-Accuracy, Precision, Recall

In [38]:
from sklearn.metrics import accuracy_score
ovo_accuracy = accuracy_score(test_set_i.target, ovo_predict_i)
print (ovo_accuracy)

0.573162939297


In [39]:
from sklearn.metrics import precision_score
ovo_precision_score = precision_score(test_set_i.target, ovo_predict_i,average='weighted')
print (ovo_precision_score)

0.56988888905


In [40]:
from sklearn.metrics import recall_score
ovo_recall_score = recall_score(test_set_i.target, ovo_predict_i,average='weighted')
print (ovo_recall_score)

0.573162939297


## NB Multiclass Classifier

In [42]:
from sklearn.naive_bayes import GaussianNB
nb_classifier_i = GaussianNB()
nb_classifier_i.fit(train_LSI_i, train_set_i.target)
nb_predict_i = nb_classifier_i.predict(test_LSI_i)
print (nb_predict_i.shape)
print (nb_predict_i[0:4])

(1565,)
[2 0 3 1]


#### NB-Multi Confusion Matrix

In [43]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_set_i.target, nb_predict_i)

array([[138, 164,  64,  26],
       [109, 129,  97,  50],
       [ 72,  51, 204,  63],
       [ 98,  19,  52, 229]])

#### NB-Multi-Accuracy, Precision, Recall

In [44]:
from sklearn.metrics import accuracy_score
nb_accuracy = accuracy_score(test_set_i.target, nb_predict_i)
print (nb_accuracy)

0.447284345048


In [45]:
from sklearn.metrics import precision_score
nb_precision_score = precision_score(test_set_i.target, nb_predict_i,average='weighted')
print (nb_precision_score)

0.450482201719


In [46]:
from sklearn.metrics import recall_score
nb_recall_score = recall_score(test_set_i.target, nb_predict_i,average='weighted')
print (nb_recall_score)

0.447284345048
