# Problem(a)

In [57]:
# from matplotlib import pyplot
import os

#define a function to count the document number 
def Count(dirname):
  count=0
  for item in os.listdir(dirname):
    count+=1
  return count

counter=[]

#plot the histogram for 20 topics
for dir in os.listdir('20news-bydate-train'):
  dir_name='20news-bydate-train/'+dir
  count1=Count(dir_name)
  counter.append(count1)

i=0;

for dir in os.listdir('20news-bydate-test'):
  #print counter[i],'\n'
  dir_name='20news-bydate-test/'+dir
  count2=Count(dir_name)
  counter[i]+=count2
  #print counter[i],'\n'
  i+=1
  
#count the document number for the two groups
new_counter=[0,0]
for dir in os.listdir('20news-bydate-train'):
  if(dir=='comp.graphics' or dir=='comp.os.ms-windows.misc' or dir=='comp.sys.ibm.pc.hardware' or dir=='comp.sys.mac.hardware'):
    dir_name='20news-bydate-train/'+dir
    count1=Count(dir_name)
    new_counter[0]+=count1
    #print (new_counter[0],'\n')
  if(dir=='rec.autos' or dir=='rec.motorcycles' or dir=='rec.sport.baseball' or dir=='rec.sport.hockey'):
    dir_name='20news-bydate-train/'+dir
    count1=Count(dir_name)
    new_counter[1]+=count1
    #print (new_counter[1],'\n')
    
for dir in os.listdir('20news-bydate-test'):
  if(dir=='comp.graphics' or dir=='comp.os.ms-windows.misc' or dir=='comp.sys.ibm.pc.hardware' or dir=='comp.sys.mac.hardware'):
    dir_name='20news-bydate-test/'+dir
    count2=Count(dir_name)
    new_counter[0]+=count2
    #print (new_counter[0],'\n')
  if(dir=='rec.autos' or dir=='rec.motorcycles' or dir=='rec.sport.baseball' or dir=='rec.sport.hockey'):
    dir_name='20news-bydate-test/'+dir
    count2=Count(dir_name)
    new_counter[1]+=count2
    #print (new_counter[1],'\n')

print ('Group1 is: ',new_counter[0],', Group2 is: ',new_counter[1])

Group1 is:  3903 , Group2 is:  3979


In [61]:
import numpy as np
import matplotlib.pyplot as plt
n = 20
values = (counter[0],counter[1],counter[2],counter[3],counter[4],counter[5],counter[6],counter[7],counter[8],counter[9],counter[10],counter[11],counter[12],counter[13],counter[14],counter[15],counter[16],counter[17],counter[18],counter[19])
fig, ax = plt.subplots()
index = np.arange(n)
bar_width = 0.35
opacity = 1.0
bars = plt.bar(index, values, bar_width,alpha = opacity, color = 'b')
plt.xlabel('Topics')
plt.xlabel('\nDocuments')
plt.title('Number of documents per topic')
plt.xticks(index + bar_width, ('atheism', 'graphics', 'windows.\nmisc', 'pc.\nhardware', 'mac.\nhardware', 'windows.x', 'forsale', 'autos', 'motorcycles', 'sport.\nbaseball', 'sport.\nhockey', 'crypt', 'electronics', 'med', 'space', 'christian', 'guns', 'mideast', 'politics.\nmisc', 'religion.\nmisc'))
plt.ylim(0,1000)

plt.legend()
plt.tight_layout()
plt.show()

C:\Users\Ziyin\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py:519: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "


# Problem(b)

In [134]:
from sklearn.feature_extraction import text
import re
import nltk 
import string
#nltk.download()

stop_words = text.ENGLISH_STOP_WORDS

from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english")

def tokenizer_fun(text):
    new_text = re.sub(r'[^A-Za-z]', " ", text)
    tokens =[word for sent in nltk.sent_tokenize(new_text) for word in nltk.word_tokenize(sent)]
    new_tokens = []
    for token in tokens:
        if re.search('[a-zA-Z]{2,}', token):
            new_tokens.append(token)     
    stem = [stemmer.stem(t) for t in new_tokens]
    return stem

from sklearn.datasets import fetch_20newsgroups
all_data = fetch_20newsgroups(subset='all', shuffle=True, random_state=42, remove=('headers','footers','quotes'))

from sklearn.feature_extraction.text import TfidfVectorizer
TFxIDF = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}',)
TFxIDF_data = TFxIDF.fit_transform(all_data.data)
count = TFxIDF_data.shape

print (count)

(18846, 72399)


# Problem(c)

In [135]:
my_list=['comp.sys.ibm.pc.hardware','comp.sys.mac.hardware','misc.forsale','soc.religion.christian']

for category in my_list:
    categories = [category]
    sub_data = fetch_20newsgroups(subset='all', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
    TFxIDF_sub = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, max_features=10, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}')
    sub_count = TFxIDF_sub.fit_transform(sub_data.data)
    #print (sub_count)
    print (TFxIDF_sub.vocabulary_.keys())
    

dict_keys(['scsi', 'mb', 'drive', 'control', 'work', 'use', 'problem', 'ani', 'disk', 'card'])
dict_keys(['drive', 'like', 'know', 'mac', 'work', 'use', 'problem', 'ani', 'appl', 'monitor'])
dict_keys(['sell', 'pleas', 'ship', 'offer', 'price', 'drive', 'use', 'includ', 'sale', 'new'])
dict_keys(['say', 'god', 'church', 'christian', 'peopl', 'believ', 'think', 'sin', 'jesus', 'know'])


# Problem(d)

In [5]:
from sklearn.decomposition import TruncatedSVD
X = TruncatedSVD(n_components=50, algorithm='arpack')
LSI = X.fit_transform(TFxIDF_data)
#print (LSI)

# Problem(e)

#### Define functions to get data or LSI for train/test set

In [69]:
categories = ['comp.graphics','comp.os.ms-windows.misc','comp.sys.ibm.pc.hardware','comp.sys.ibm.pc.hardware','rec.autos','rec.motorcycles','rec.sport.baseball','rec.sport.hockey']

def data_fun(train_or_test):
    if(train_or_test == 'train'):
        data = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
    if(train_or_test == 'test'):
        data = fetch_20newsgroups(subset='test', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
    return data  

def LSI_fun(train_or_test):
    if(train_or_test == 'train'):
        data = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
        TFxIDF_sub = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}',)
        TFxIDF_sub_data = TFxIDF_sub.fit_transform(data.data)
        Y = TruncatedSVD(n_components=50, algorithm='arpack')
        sub_LSI = Y.fit_transform(TFxIDF_sub_data)
    if(train_or_test == 'test'):
        data = fetch_20newsgroups(subset='test', categories=categories, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
        TFxIDF_sub = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}',)
        TFxIDF_sub_data = TFxIDF_sub.fit_transform(data.data)
        Y = TruncatedSVD(n_components=50, algorithm='arpack')
        sub_LSI = Y.fit_transform(TFxIDF_sub_data)
    return sub_LSI 

#new_LSI = LSI_fun('train')
#print (new_LSI.shape)

#new_LSI = LSI_fun('test')
#print (new_LSI.shape)

#### SVM classifier

In [70]:
from sklearn import svm
lin_clf = svm.LinearSVC()
# print(all_data.target)
train_LSI = LSI_fun('train')
train_set = data_fun('train')

train_target_group = [ int(x / 4) for x in train_set.target]
# print(train_target_group)
print(train_set.target[0:20])
# lin_clf.fit(train_LSI, train_set.target)
lin_clf.fit(train_LSI, train_target_group)
#lin_clf.fit(train_LSI, train_set.target)

[5 5 7 4 6 1 2 4 6 0 7 2 0 7 5 7 5 2 5 5]


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [71]:
test_LSI = LSI_fun('test')
print(test_LSI.shape)
svm_predicted = lin_clf.predict(test_LSI)
print (svm_predicted[0:20])

(2765, 50)
[1 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1 0 1]


#### SVM-ROC Curve

In [72]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
test_set = data_fun('test')
test_target_group = [ int(x / 4) for x in test_set.target]
y_score_test = lin_clf.decision_function(test_LSI)


#print(test_target_group[0:10])
#print(y_score_test.shape)
#print(y_score_test[0:10])

fpr, tpr, thresholds = roc_curve(test_target_group, y_score_test)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, lw=1, label='ROC fold (area = %0.2f)' % roc_auc)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.show()

#### SVM-Confusion Matrix

In [73]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_target_group, svm_predicted)

array([[ 863,  312],
       [  64, 1526]])

#### SVM-Accuracy, Precision, Recall

In [74]:
from sklearn.metrics import accuracy_score
svm_accuracy = accuracy_score(test_target_group, svm_predicted)
print (svm_accuracy)

0.864014466546


In [75]:
from sklearn.metrics import precision_score
svm_precision_score = precision_score(test_target_group, svm_predicted)
print (svm_precision_score)

0.830250272035


In [76]:
from sklearn.metrics import recall_score
svm_recall_score = recall_score(test_target_group, svm_predicted)
print (svm_recall_score)

0.959748427673


#### SVM-Recall and Precision

In [77]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
precision = dict()
recall = dict()
average_precision = dict()
precision, recall, _ = precision_recall_curve(test_target_group,y_score_test)
average_precision = average_precision_score(test_target_group, y_score_test)
print (precision[0:10])
print (recall[0:10])

[ 0.64035441  0.64020951  0.64046755  0.64072581  0.64098427  0.64124294
  0.64150182  0.6417609   0.6420202   0.64227971]
[ 1.          0.99937107  0.99937107  0.99937107  0.99937107  0.99937107
  0.99937107  0.99937107  0.99937107  0.99937107]


# Problem(f)

In [78]:
from sklearn.cross_validation import KFold
kf = KFold(len(train_target_group), n_folds=5,shuffle=False,random_state=None)
len(kf)
print(kf)


sklearn.cross_validation.KFold(n=4154, n_folds=5, shuffle=False, random_state=None)


In [79]:
from sklearn import svm
#initialize a matrix with 7 rows(lamda) and 5 columns(5 validation)
matrix = [[0]*7 for i in range(5)]
i = 0
j = 0

for train_index, test_index in kf:
    X_train, X_test = train_LSI[train_index], train_LSI[test_index]
    for k in [-3, -2, -1, 0, 1, 2, 3]:
        X_train_target_group = [ int(x / 4) for x in train_set.target[train_index]]
        X_test_target_group = [ int(x / 4) for x in train_set.target[test_index]]
        
        soft_svm_clf = svm.LinearSVC(C=10**k)
        soft_svm_clf.fit(X_train, X_train_target_group)
        score = soft_svm_clf.score(X_test, X_test_target_group)        
        matrix[i][j]=score
        j=j+1
    i=i+1
    j=0


In [80]:
ave_score = list(map(lambda x: (x[0]+x[1]+x[2]+x[3]+x[4])/5, zip(matrix[0], matrix[1], matrix[2], matrix[3], matrix[4])))
#print average_s
value = max(ave_score)
index=ave_score.index(value)
#print index
penalty = [-3, -2, -1, 0, 1, 2, 3]
print ('The best penalty value is',10**penalty[index])

The best penalty value is 100


In [81]:
soft_clf = svm.LinearSVC(C=10**1)
soft_clf.fit(train_LSI, train_target_group)
soft_svm_predicted = soft_clf.predict(test_LSI)

score = soft_clf.score(test_LSI, test_target_group)
print (score)

0.852802893309


### Soft_SVM Confusion Matrix

In [82]:
from sklearn.metrics import confusion_matrix

confusion_matrix(test_target_group, soft_svm_predicted)

array([[ 847,  328],
       [  79, 1511]])

### Soft_clf-Accuracy, Precision, Recall

In [83]:
from sklearn.metrics import accuracy_score
soft_clf_accuracy = accuracy_score(test_target_group, soft_svm_predicted)
print (soft_clf_accuracy)

0.852802893309


In [84]:
from sklearn.metrics import precision_score
soft_clf_precision_score = precision_score(test_target_group, soft_svm_predicted)
print (soft_clf_precision_score)

0.821642196846


In [85]:
from sklearn.metrics import recall_score
soft_clf_recall_score = recall_score(test_target_group, soft_svm_predicted)
print (soft_clf_recall_score)

0.950314465409


# Problem(g)

#### NB classifier

In [86]:
from sklearn.naive_bayes import GaussianNB
nb_clf = GaussianNB()
nb_clf.fit(train_LSI, train_target_group)
nb_predicted = nb_clf.predict(test_LSI)
print (nb_predicted.shape)
print (nb_predicted[0:10])

(2765,)
[1 0 1 0 0 0 1 0 0 1]


#### NB-ROC Curve

In [87]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
test_set = data_fun('test')
test_target_group = [ int(x / 4) for x in test_set.target]
y_score_test_nb = nb_clf.predict_proba(test_LSI)[:,1]


print(y_score_test_nb.shape)
print(y_score_test_nb[0:10])

fpr, tpr, thresholds = roc_curve(test_target_group, y_score_test_nb)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, lw=1, label='ROC fold (area = %0.2f)' % roc_auc)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.show()

(2765,)
[  9.99998535e-01   2.41728915e-06   9.99995110e-01   8.35444547e-19
   1.09664432e-04   2.34099449e-53   9.99975396e-01   1.35612443e-07
   4.98885655e-01   9.99979288e-01]


#### NB-Confusion Matrix

In [88]:
from sklearn.metrics import confusion_matrix

confusion_matrix(test_target_group, nb_predicted)

array([[936, 239],
       [764, 826]])

#### NB-Accuracy, Precision, Recall

In [89]:
from sklearn.metrics import accuracy_score
nb_accuracy = accuracy_score(test_target_group, nb_predicted)
print (nb_accuracy)

0.637251356239


In [90]:
from sklearn.metrics import precision_score
nb_precision_score = precision_score(test_target_group, nb_predicted)
print (nb_precision_score)

0.77558685446


In [91]:
from sklearn.metrics import recall_score
nb_recall_score = recall_score(test_target_group, nb_predicted)
print (nb_recall_score)

0.519496855346


#### NB-Recall and Precision

In [92]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
y_score_test_nb = nb_clf.predict_proba(test_LSI)[:,1]
precision = dict()
recall = dict()
average_precision = dict()
precision, recall, _ = precision_recall_curve(test_target_group,y_score_test_nb)
average_precision = average_precision_score(test_target_group, y_score_test_nb)
print (precision[0:10])
print (recall[0:10])

[ 0.57504521  0.70386007  0.70392749  0.70381587  0.70345664  0.70309654
  0.70291616  0.70237371  0.70365854  0.7045177 ]
[ 1.          0.73396226  0.7327044   0.73081761  0.72955975  0.72830189
  0.72767296  0.72578616  0.72578616  0.72578616]


# Problem(h)

#### LR classifier

In [93]:
from sklearn import linear_model, datasets
logreg = linear_model.LogisticRegression(C=1e5)
logreg.fit(train_LSI, train_target_group)
lr_predicted = logreg.predict(test_LSI)
print (lr_predicted.shape)
print (lr_predicted[0:10])

(2765,)
[1 0 1 0 0 1 1 0 0 1]


#### LR-ROC Curve

In [94]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
test_set = data_fun('test')
test_target_group = [ int(x / 4) for x in test_set.target]
y_score_test_lr = logreg.decision_function(test_LSI)
#y_score_test_lr = logreg.predict_proba(test_LSI)[:,1]

print(y_score_test_lr.shape)
print(y_score_test_lr[0:10])

fpr, tpr, thresholds = roc_curve(test_target_group, y_score_test_lr)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, lw=1, label='ROC fold (area = %0.2f)' % roc_auc)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.show()

(2765,)
[  4.70921762 -19.2542064    4.15699709  -5.53790364 -30.72647309
  17.67154364   3.96866553 -24.63030585  -6.16904487   5.70334832]


#### LR-Confusion Matrix

In [95]:
from sklearn.metrics import confusion_matrix

confusion_matrix(test_target_group, lr_predicted)

array([[ 850,  325],
       [ 124, 1466]])

#### LR-Accuracy, Precision, Recall

In [96]:
from sklearn.metrics import accuracy_score
lr_accuracy = accuracy_score(test_target_group, lr_predicted)
print (lr_accuracy)

0.837613019892


In [97]:
from sklearn.metrics import precision_score
lr_precision_score = precision_score(test_target_group, lr_predicted)
print (lr_precision_score)

0.818537130095


In [98]:
from sklearn.metrics import recall_score
lr_recall_score = recall_score(test_target_group, lr_predicted)
print (lr_recall_score)

0.922012578616


#### LR-Recall and Precision

In [99]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
y_score_test_lr = logreg.decision_function(test_LSI)
precision = dict()
recall = dict()
average_precision = dict()
precision, recall, _ = precision_recall_curve(test_target_group,y_score_test_lr)
average_precision = average_precision_score(test_target_group, y_score_test_lr)
print (precision[0:10])
print (recall[0:10])

[ 0.61795569  0.61780715  0.61804745  0.61828794  0.61852861  0.61876947
  0.61901052  0.61925175  0.61949318  0.61973479]
[ 1.          0.99937107  0.99937107  0.99937107  0.99937107  0.99937107
  0.99937107  0.99937107  0.99937107  0.99937107]


# Part (i)

#### Define functions to get data or LSI for train/test set

In [117]:
categories_i = ['comp.sys.ibm.pc.hardware','comp.sys.mac.hardware','misc.forsale','soc.religion.christian']

def data_fun_i(train_or_test):
    if(train_or_test == 'train'):
        data = fetch_20newsgroups(subset='train', categories=categories_i, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
    if(train_or_test == 'test'):
        data = fetch_20newsgroups(subset='test', categories=categories_i, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
    return data

def LSI_fun_i(train_or_test):
    if(train_or_test == 'train'):
        data = fetch_20newsgroups(subset='train', categories=categories_i, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
        TFxIDF_sub = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}',)
        TFxIDF_sub_data = TFxIDF_sub.fit_transform(data.data)
        Y = TruncatedSVD(n_components=50, algorithm='arpack')
        sub_LSI = Y.fit_transform(TFxIDF_sub_data)
    if(train_or_test == 'test'):
        data = fetch_20newsgroups(subset='test', categories=categories_i, shuffle=True, random_state=42, remove=('headers','footers','quotes'))
        TFxIDF_sub = TfidfVectorizer(analyzer='word',tokenizer=tokenizer_fun, stop_words=stop_words,token_pattern='[a-zA-Z]{2,}',)
        TFxIDF_sub_data = TFxIDF_sub.fit_transform(data.data)
        Y = TruncatedSVD(n_components=50, algorithm='arpack')
        sub_LSI = Y.fit_transform(TFxIDF_sub_data)
    return sub_LSI

In [118]:
from sklearn.multiclass import OneVsRestClassifier 
from sklearn.multiclass import OneVsOneClassifier 
from sklearn.svm import LinearSVC
train_LSI_i = LSI_fun_i('train')
train_set_i = data_fun_i('train')
test_LSI_i = LSI_fun_i('test')
test_set_i = data_fun_i('test')
#train_target_group_i = [ int(x / 10) for x in train_set_i.target]
#test_target_group_i = [int(x / 10) for x in test_set_i.target]

## one vs rest classifier

In [119]:
ovr_classifier_i = OneVsRestClassifier (LinearSVC())
ovr_classifier_i.fit(train_LSI_i, train_set_i.target)
ovr_predict_i = ovr_classifier_i.predict(test_LSI_i)
#print (ovr_predict_i[0:4])
print (ovr_predict_i)

[2 0 2 ..., 0 2 3]


#### OVR-Confusion Matrix

In [120]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_set_i.target, ovr_predict_i)

array([[149, 178,  60,   5],
       [124,  94, 140,  27],
       [ 37,  35, 308,  10],
       [  4,   5,  28, 361]])

#### OVR-Accuracy, Precision, Recall

In [121]:
from sklearn.metrics import accuracy_score
ovr_accuracy = accuracy_score(test_set_i.target, ovr_predict_i)
print (ovr_accuracy)

0.582747603834


In [122]:
from sklearn.metrics import precision_score
ovr_precision_score = precision_score(test_set_i.target, ovr_predict_i,average='weighted')
print (ovr_precision_score)

0.563982043464


In [123]:
from sklearn.metrics import recall_score
ovr_recall_score = recall_score(test_set_i.target, ovr_predict_i,average='weighted')
print (ovr_recall_score)

0.582747603834


## one vs one classifier

In [124]:
ovo_classifier_i = OneVsOneClassifier (LinearSVC())
ovo_classifier_i.fit(train_LSI_i, train_set_i.target)
ovo_predict_i = ovo_classifier_i.predict(test_LSI_i)
print (ovo_predict_i.shape)
print (ovo_predict_i)

(1565,)
[2 0 2 ..., 0 2 3]


#### OVO-Confusion Matrix

In [125]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_set_i.target, ovo_predict_i)

array([[156, 175,  59,   2],
       [145,  94, 136,  10],
       [ 37,  37, 310,   6],
       [  5,  10,  35, 348]])

#### OVO-Accuracy, Precision, Recall

In [126]:
from sklearn.metrics import accuracy_score
ovo_accuracy = accuracy_score(test_set_i.target, ovo_predict_i)
print (ovo_accuracy)

0.580191693291


In [127]:
from sklearn.metrics import precision_score
ovo_precision_score = precision_score(test_set_i.target, ovo_predict_i,average='weighted')
print (ovo_precision_score)

0.571965590504


In [128]:
from sklearn.metrics import recall_score
ovo_recall_score = recall_score(test_set_i.target, ovo_predict_i,average='weighted')
print (ovo_recall_score)

0.580191693291


## NB Multiclass Classifier

In [129]:
from sklearn.naive_bayes import GaussianNB
nb_classifier_i = GaussianNB()
nb_classifier_i.fit(train_LSI_i, train_set_i.target)
nb_predict_i = nb_classifier_i.predict(test_LSI_i)
print (nb_predict_i.shape)
print (nb_predict_i[0:4])

(1565,)
[2 0 3 2]


#### NB-Multi Confusion Matrix

In [130]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_set_i.target, nb_predict_i)

array([[137, 161,  72,  22],
       [109, 127, 105,  44],
       [ 79,  45, 204,  62],
       [ 97,  18,  56, 227]])

#### NB-Multi-Accuracy, Precision, Recall

In [131]:
from sklearn.metrics import accuracy_score
nb_accuracy = accuracy_score(test_set_i.target, nb_predict_i)
print (nb_accuracy)

0.444089456869


In [132]:
from sklearn.metrics import precision_score
nb_precision_score = precision_score(test_set_i.target, nb_predict_i,average='weighted')
print (nb_precision_score)

0.449276631965


In [133]:
from sklearn.metrics import recall_score
nb_recall_score = recall_score(test_set_i.target, nb_predict_i,average='weighted')
print (nb_recall_score)

0.444089456869
